@startuml aquitetura

interface "select data" as selectData
interface "import data" as imp_data
interface "process data" as process_data
interface "gestão input" as gest_input
interface "gestão output" as gest_output
interface "gestão processos" as gest_process
interface "gestão etapas" as gest_etapas
interface "PCF total" as pcf_tot
interface "relatorios" as relatorios 
interface "Gestao Flow" as gest_flow 

[Data] as data_comp
data_comp - selectData

[Data Ingestion] as data_ingestion
data_ingestion --( selectData
data_ingestion - imp_data

[Data Processing] as data_processing
data_processing - process_data
data_processing --( imp_data

[Input] as input_comp
input_comp - gest_input

/'
Ver se os csv também tem outputs
'/
[Output] as output_comp
output_comp - gest_output
/'Meter para retornar'/
[Flow] as Flow 
Flow --( gest_input
Flow --( gest_output
Flow --( process_data
Flow - gest_flow

[Processo] as processo
processo -- gest_process
processo --( gest_flow


[Etapa produção] as etapa
gest_etapas -- etapa
etapa -( gest_process

[Calculator] as calculator
calculator --( gest_etapas
calculator -- pcf_tot
calculator -- relatorios

@enduml