@startuml aquitetura
/'Necessito encaixar os flows em algum ladao'/

interface "data" as data
/'Estes primary data tanto são dados de componenetes
como dados de energia ou água'/
interface "primary data" as prim_data
interface "secunday data" as sec_data

/'Se calhar trocar input por fluxo, porque é um fluxo de 
entrada e não input'/
interface "input" as input
interface "output" as output

interface "produtos" as produto
interface "emissões" as emissoes

interface "consumo enegia" as consumo_ener
interface "perda total" as perda_tot
interface "emissao media ponderada" as emiss_med_ponde
interface "PCF total" as pcf_tot

interface "material" as material
interface "energia" as energia

interface "perdas" as perdas

/'
O data Ingestion e o que lê os ficheiros CSV

Ver se o retorno do Data Ingestion está correto, ou
outro nome.
'/
[Company] as company
company - prim_data

[Missing primary data] as miss_prim
miss_prim - sec_data

[Data Ingestion] as data_ingestion
data_ingestion - data

data_ingestion --( prim_data
data_ingestion --( sec_data

[Data Processing] as data_processing
data_processing - material
data_processing - energia
data_processing --( data

[Input] as input_comp
input_comp --( energia
input_comp --( material
input_comp - input

[Processo Unitario] as processo_unitario
processo_unitario - produto 
processo_unitario - emissoes
processo_unitario --( input

[Processo Agrado] as processo_agregado 


[Output] as output_comp
output_comp -- output
output_comp --( produto
output_comp --( emissoes
 

[Calculator] as calculator
calculator --( output
calculator --( input

calculator - perdaTot
calculator - consumo_ener
calculator - emiss_med_ponde
calculator - pcf_tot


[PCF] as PCF
PCF - PCF_Data
PCF --( perda_tot
PCF --( consumo_ener
PCF --( emiss_med_ponde
PCF --( pcf_tot

/'
Tipos de relatorios
'/
interface "relatorio emissoes" as rel_emissoes /'Este mostra todos as etapas de produção que poluiram'/
interface "relatorio perdas" as rel_perdas /'Mostra todas as perdas obtidas na produção do produto'/
[Relatorios] as relatorio
relatorio --( PCF_Data
relatorio - rel_emissoes
relatorio -- rel_perdas
/'
O output neste caso representa um processo unitario
'/
[Etapa Produção] as etapa
etapa -( output
etapa - perdas
etapa - emissoes
/'
Componentes que tenho duvidas ou tenho a certeza que devem existir mas ainda não encontrei onde colocar
'/

[Flows] as flows
flows - flow

/'Ligações que não sei se são necessárias ou se deviam existir sequer'/

 


@enduml