@startuml

/'Inico das classes'/

abstract class Flow {
    String name
    String categoria
    double fator_emissao
    String unidade
}

/'Nota o elemenentar flow tanto pode ser um input
ou output'/
class Elemental_Flow extends Flow{

}

/'Ocorre entre processos, ou'/
class Product_Flow extends Elemental_Flow {

}

/'
Corresponde as substancias/ objetos que serao
"alienados" de alguma forma
'/
class Waste_Flow extends Elemental_Flow {
    Perdas perda
}

class Perdas {
    double amount_necessary
    String unidade
    double valor_ajustado_waste
    double emissoes
    double emissoes_ajustada
}

/' Aqui guarda os Fluxos de entrada e de saida
Os de entrada corresponde a tudo o que entra para produzir
o produto
Os fluxos de saida a tudo o gerado pela produção

O fator_emissão não até que ponto pode estar cá
'/
class Input_Outputs {
    String name
    typeInput type 
    Flow flow
    double quantidade 
    String unidade
    double fator_emissao
}

class Input extends Input_Outputs {

}

class Output extends Input_Outputs {

}

/'Esta probavelmente e desnecessária'/
class Emissoes extends Input_Outputs {

}

/'Esta classe seria um processo unitário

Segundo a figura 2 - Processo, Fluxos e Sistema
cada processo tem um input e um output
'/
class Processo {
    String nomePro
    Input input
    Output output
}

/'
Este classe representa um processo agregado

Ver se o name_processos é necessário
'/
class Processos {
    String name_processos
    Processo processo
    String categoria
    String descricao
    String localizacao
    String unidade
}

class Etapa_Producao {
    Processo etapa
    Processos processo_prod
    double consumo_eletricidade
}

/'Classes a repensar'/

/'
Provavelemente só é preciso 1 class 
'/
class Material {
    String name
    Processos material_flow
    Processos processing_flows
    Processo asembly_flow
    String typical_unit
    double amount
}

class Component extends Material {
    Material[] primary_materials 
} 

/'
Tabela para o calculo de CO2e 
'/
/'
Não sei se por ser abstrata irá dar problemas 
proporcao --> %
fator emissao --> kgCO₂e/kWh
'/

abstract class Power_Source {
    String name
    double proporcao 
    double fator_emissao
}

/'Energia Primaria --> MJ/kWh
uso de agua --> litros/kWh'/
class Mix_Eletricty extends Power_Source {
    double energia_primaria
    double uso_agua
}

class Weighted_Average extends Power_Source {
    double weighted_average
}

/'
Esta classe serve para calcular o valor total
de emissao de kgCo2e/kWh, para quando a empresa
fornece todos os gasto ou quando não temos acesso
a eles
'/
class Eletricty_Emission {
    Power_Source[] power_source
    double tot_emission
}

/' das classes'/
@enduml